### ISSUE TITLE
Upgrade RStudio version

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/rstudio-base#2]
We need to upgrade our base image to RStudio 3.5.x.  We currently use [rocker/ropensci](https://github.com/rocker-org/ropensci), which has the latest version 3.4.x.  

For now, we'll move to [rocker/geospatial](https://github.com/rocker-org/binder/blob/master/3.5.1/Dockerfile). @cboettig -- we'd welcome your input here.

**Comment by cboettig** [comment]
@craig-willis yes, `rocker/geospatial` is definitely a better choice for a base image, it's much more actively maintained and widely used.  Note that `latest` and `devel` versions are built nightly with the latest versions of packages etc.   as you probably know, you can use any of the tagged versions to get stable builds, e.g. `rocker/geospatial:3.5.1` or `rocker/geospatial:3.4.4` etc.  The most recent tag continues to pull down newer versions of packages when re-built, but the image is only rebuilt once a month (can be better for caching).  Once a version is not current, the package versions are locked to the last day it was current, details on https://github.com/rocker-org/rocker-versioned.  

`rocker/ropensci` isn't quite up to date, mostly used internally for package building and testing of the ropensci drat repo.  `geospatial` builds on `verse` and should have most common dependencies.

**Comment by craig-willis** [comment]
Thanks much, @cboettig. We'll move ahead with `rocker/geospatial`.

**Comment by Xarthisius** [comment]
Fixed in https://github.com/whole-tale/rstudio-base/commit/1728ada20a6738fdc75291fc2173d34352faa0a9
